# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 6",
   "iPhone 6 Plus",
   "iPhone 5",
   "iPhone 4s",
#   "iPad Retina",
#   "iPad Pro"
])

languages([
  "en-GB"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# The name of the scheme which contains the UI Tests
scheme "Astronomy Picture Of The Day - NASAs APOD"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
#project ""
 workspace "/Users/darrenleith/Google\ Drive/Swift/Astronomy\ Picture\ Of\ The\ Day\ -\ NASAs\ APOD/Astronomy\ Picture\ Of\ The\ Day\ -\ NASAs\ APOD.xcodeproj/project.xcworkspace/"

# For more information about all available options run
# snapshot --help
